### ISSUE TITLE
G.cn奇怪的解析问题。

### ISSUE THREAD

**Issue by Iy204** [semigodking/cdns#13]
尝试了很多上游。默认的Google的Opendns443 5353端口PublicDNS的。
g.cn是我手机WIFI检测是否可用的网址。
正确的解析不是应该是google北京的服务器。203.208.51.X。
但是在cdns总是被解析到美国去，让WIFI总是感叹号认为网络不可链接。

`root@OpenWrt:~# dig g.cn @127.0.0.1 -p 1053

; <<>> DiG 9.9.8-P3 <<>> g.cn @127.0.0.1 -p 1053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54378
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;g.cn.				IN	A

;; ANSWER SECTION:
g.cn.			1	IN	A	216.58.199.99

;; AUTHORITY SECTION:
g.cn.			520	IN	NS	ns1.google.com.
g.cn.			520	IN	NS	ns2.google.com.
g.cn.			520	IN	NS	ns3.google.com.
g.cn.			520	IN	NS	ns4.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.		172484	IN	A	216.239.32.10
ns2.google.com.		172473	IN	A	216.239.34.10
ns3.google.com.		172473	IN	A	216.239.36.10
ns4.google.com.		172475	IN	A	216.239.38.10

;; Query time: 48 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Fri Oct 27 15:26:14 CST 2017
;; MSG SIZE  rcvd: 195
`
重复不停的尝试解析g.cn。中间也出现过正确的结果。
root@OpenWrt:~# dig g.cn @127.0.0.1 -p 1053

; <<>> DiG 9.9.8-P3 <<>> g.cn @127.0.0.1 -p 1053
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37344
;; flags: qr rd ra; QUERY: 1, ANSWER: 4, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;g.cn.				IN	A

;; ANSWER SECTION:
g.cn.			299	IN	A	203.208.43.119
g.cn.			299	IN	A	203.208.43.120
g.cn.			299	IN	A	203.208.43.111
g.cn.			299	IN	A	203.208.43.127

;; Query time: 60 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Fri Oct 27 15:26:09 CST 2017
;; MSG SIZE  rcvd: 97
十次里只有一两次是这个结果。

cdns是自己编译的ghostry/openwrt-gmod。路由上是openwrt CC 15.05.1

**Comment by Iy204** [comment]
其他Youtube之类的解析使用cdns是正确的。
我的网络本身有DNS劫持问题。除了OpenDNS非53端口和中科大的DNS。
其他的国内外DNS在请求Youtube这类网站时就会被劫持。
使用DIG命令的时候特别明显。一些海外DNS本身延迟很高。查询国内网站查询时间在100MS以上。
可是一查询youtube之类的dig的查询时间一下子缩短到20ms。

**Comment by semigodking** [comment]
这个很正常啊，因为使用境外的dns解析，当然结果优先选择境外的cdn之类的的。对于.cn下的域名，我建议直接在DNSmasq
里配置让你isp上默认提供的服务器来解析。其他的用cdns来解析。

**Comment by semigodking** [comment]
比如，我在dnsmasq的配置文件里加了这样的

server=/.cn/211.136.192.6
server=/.126.net/211.136.192.6
