### ISSUE TITLE
config option for disable ipv6 query

### ISSUE THREAD

**Issue by zhaibin18** [semigodking/cdns#16]
currently there is ipv6 support for cdns, but in my internet environment there is no need for ipv6 query,so can you please add a option in config file to disable ipv6 query,many thanks!

**Comment by semigodking** [comment]
@zhaibin18 if there's no ipv6 up stream dns server configured, no query can be sent to ipv6 dns servers. If you do not want cdns to listen on IPv6 addresses, just do not set "listen_ip" to '::' or other ipv6 addresses.
