### ISSUE TITLE
特定域名无法解析的问题

### ISSUE THREAD

**Issue by zhaibin18** [semigodking/cdns#19]
如下所示，解析www.nytimes.com会超时，www.nytimes.com和www.google.com的区别是有CNAME，日志和tcpdump的数据在附件中。

```
dig www.nytimes.com -p 8053 @10.1.2.1

; <<>> DiG 9.14.12 <<>> www.nytimes.com -p 8053 @10.1.2.1
;; global options: +cmd
;; connection timed out; no servers could be reached


dig www.google.com -p 8053 @10.1.2.1

; <<>> DiG 9.14.12 <<>> www.google.com -p 8053 @10.1.2.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26109
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 9

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         102     IN      A       142.250.199.68

;; AUTHORITY SECTION:
google.com.             86888   IN      NS      ns3.google.com.
google.com.             86888   IN      NS      ns2.google.com.
google.com.             86888   IN      NS      ns1.google.com.
google.com.             86888   IN      NS      ns4.google.com.

;; ADDITIONAL SECTION:
ns1.google.com.         101839  IN      A       216.239.32.10
ns1.google.com.         101839  IN      AAAA    2001:4860:4802:32::a
ns2.google.com.         93262   IN      A       216.239.34.10
ns2.google.com.         93705   IN      AAAA    2001:4860:4802:34::a
ns3.google.com.         93263   IN      A       216.239.36.10
ns3.google.com.         93705   IN      AAAA    2001:4860:4802:36::a
ns4.google.com.         101839  IN      A       216.239.38.10
ns4.google.com.         101839  IN      AAAA    2001:4860:4802:38::a

;; Query time: 86 msec
;; SERVER: 10.1.2.1#8053(10.1.2.1)
;; WHEN: Sun Feb 21 12:49:28 CST 2021
;; MSG SIZE  rcvd: 307
```
[cdns.zip](https://github.com/semigodking/cdns/files/6017204/cdns.zip)

**Comment by semigodking** [comment]
我初步看了一下，没有看出问题出在哪里。由于log信息不够，也不能准确地对应log与你的抓包。根据包结构和代码分析，按说是不应该有问题的。我需要找时间试试。

**Comment by semigodking** [comment]
A quick test shows that it works for me.

`$ dig www.nytimes.com -p 1054 @192.168.1.1

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.nytimes.com -p 1054 @192.168.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46505
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;www.nytimes.com.               IN      A

;; ANSWER SECTION:
www.nytimes.com.        190     IN      CNAME   www.prd.map.nytimes.com.
www.prd.map.nytimes.com. 84     IN      CNAME   nytimes.map.fastly.net.
nytimes.map.fastly.net. 30      IN      A       151.101.77.164

;; AUTHORITY SECTION:
fastly.NET.             3204    IN      NS      ns4.fastly.net.
fastly.NET.             3204    IN      NS      ns2.fastly.net.
fastly.NET.             3204    IN      NS      ns1.fastly.net.
fastly.NET.             3204    IN      NS      ns3.fastly.net.

;; ADDITIONAL SECTION:
ns1.fastly.NET.         1906    IN      A       23.235.32.32
ns2.fastly.NET.         1906    IN      A       104.156.80.32
ns3.fastly.NET.         1906    IN      A       23.235.36.32
ns4.fastly.NET.         1906    IN      A       104.156.84.32

;; Query time: 46 msec
;; SERVER: 192.168.1.1#1054(192.168.1.1)
;; WHEN: Mon Feb 22 23:40:12 CST 2021
;; MSG SIZE  rcvd: 284`



```
23:40:03.470565 IP (tos 0x4, ttl 72, id 4708, offset 0, flags [DF], proto UDP (17), length 77)
    202.14.67.4.53 > 172.16.108.123.43857: 46505 1/0/0 www.nytimes.com. A 118.184.26.113 (49)
        0x0000:  4504 004d 1264 4000 4811 fa99 ca0e 4304
        0x0010:  ac10 6c7b 0035 ab51 0039 ac56 b5a9 8180
        0x0020:  0001 0001 0000 0000 0377 7777 076e 7974
        0x0030:  696d 6573 0363 6f6d 0000 0100 01c0 0c00
        0x0040:  0100 0100 0000 cf00 0476 b81a 71
23:40:03.502786 IP (tos 0x4, ttl 236, id 22143, offset 0, flags [DF], proto UDP (17), length 312)
    202.14.67.4.53 > 172.16.108.123.43857: 46505 3/4/5 www.nytimes.com. CNAME www.prd.map.nytimes.com., www.prd.map.nytimes.com. CNAME nytimes.map.fastly.net., nytimes.map.fastly.net. A 151.101.77.164 (284)
        0x0000:  4504 0138 567f 4000 ec11 1193 ca0e 4304
        0x0010:  ac10 6c7b 0035 ab51 0124 184b b5a9 8180
        0x0020:  0001 0003 0004 0005 0377 7777 076e 7974
        0x0030:  696d 6573 0363 6f6d 0000 0100 01c0 0c00
        0x0040:  0500 0100 0000 be00 0e03 7777 7703 7072
        0x0050:  6403 6d61 70c0 10c0 2d00 0500 0100 0000
        0x0060:  5400 1807 6e79 7469 6d65 7303 6d61 7006
        0x0070:  6661 7374 6c79 036e 6574 00c0 4700 0100
        0x0080:  0100 0000 1e00 0497 654d a406 6661 7374
        0x0090:  6c79 034e 4554 0000 0200 0100 000c 8400
        0x00a0:  0603 6e73 34c0 53c0 6f00 0200 0100 000c
        0x00b0:  8400 0603 6e73 32c0 53c0 6f00 0200 0100
        0x00c0:  000c 8400 0603 6e73 31c0 53c0 6f00 0200
        0x00d0:  0100 000c 8400 0603 6e73 33c0 5303 6e73
        0x00e0:  31c0 6f00 0100 0100 0007 7200 0417 eb20
        0x00f0:  2003 6e73 32c0 6f00 0100 0100 0007 7200
        0x0100:  0468 9c50 2003 6e73 33c0 6f00 0100 0100
        0x0110:  0007 7200 0417 eb24 2003 6e73 34c0 6f00
        0x0120:  0100 0100 0007 7200 0468 9c54 2000 0029
        0x0130:  1000 0000 0000 0000
1614008403.504581 cdns.c:289 verify_response(...) Possible good response (+edns)
1614008403.504689 cdns.c:367 cdns_readcb(...) pktlen: 284 rtt_ms: 42 avg rtt: 35 verify_rc: 1
1614008403.505083 cdns.c:328 cdns_drop_request(...) dropping request @ state: 3
```

**Comment by zhaibin18** [comment]
很奇怪，重启cdns就恢复了，过段时间就又不响应了。
没有响应的时候cdns发了三次dns请求给上游，从tcpdump数据库带edns的数据没有污染，而有响应的时候，只有一次dns请求。
无响应tcpdump文件:cdns1.out，重启cdns正常的tcpdump文件:cdns2.out
[cdns.zip](https://github.com/semigodking/cdns/files/6026407/cdns.zip)

**Comment by semigodking** [comment]
我略微更新了一下，修正了一下log，并没有解决任何问题。
我建议你在下次出问题的时候，你要把客户端到CDNS的包也抓上。根据你的log来看，怀疑response是在你网络那丢掉的。
zhaibin18 <notifications@github.com> 于 2021年2月23日周二 10:14写道：

**Comment by zhaibin18** [comment]
用最新的版本抓了更多的数据，另外10.1.2.1就是本机测试，没有经过网络设备。
[cdns_0224.tar.gz](https://github.com/semigodking/cdns/files/6032519/cdns_0224.tar.gz)

**Comment by semigodking** [comment]
原因有两种可能：
1. 服务器返回的真实response由于某种误判，导致IP被加入了黑名单，所以后续请求发现IP在黑名单中，直接就丢弃了。
2. 正确IP出现在DNS抢答中，导致IP被加入了黑名单，所以后续请求发现IP在黑名单中，直接就丢弃了。
我目前猜测，大概率是第2种情况。个别网站的 IP 被用来做ＤＮＳ抢答的黑洞了。按说，这么巧你要访问黑名单上的ｉｐ对应的网站概率也不大，居然被你碰到。 目前没有特别好的解决方案。
你可以做这么一个测试，注释掉　cdns.c 中第295行，然后编译测试。根据你提供的server的情况来看，似乎不用 黑名单也不会影响准确率。

**Comment by semigodking** [comment]
刚又做了个提交，应该能解决nytimes这个特殊情况。

**Comment by zhaibin18** [comment]
可能是第二种情况，运行了一天目前没有重现问题。
