### ISSUE TITLE
excellent!

### ISSUE THREAD

**Issue by wang20150419** [semigodking/cdns#2]
替代了路由器里的 chinadns，运行正常。
DNS解析速度很快。
感觉好神奇，想知道原理是啥？

**Comment by semigodking** [comment]
给发出去的DNS请求加上一个EDNS option，只要目标DNS服务器支持 EDNS
的话，它也会带回这个option，而DNS抢答的似乎不会带这个option。主要靠这个option来判断。所以要求远端服务器支持EDNS才能正常工作。

2016年10月25日 19:49，"wang20150419" notifications@github.com写道：

**Comment by semigodking** [comment]
没发出去？！

2016年10月26日 07:52，"Semigod King" semigodking@gmail.com写道：

**Comment by y9c** [comment]
没懂。。
例子中两个ip，如果ip（8.8.8.8）已经别墙了，还能完成DNS请求么？

```bash
        {
            "ip_port": "203.80.96.10"
        },
        {
            "ip_port": "8.8.8.8:53"
        }

```

**Comment by semigodking** [comment]
可以换成别的境外DNS, 你可以添加多个

yech <notifications@github.com>于2017年8月2日周三 07:51写道：

**Comment by y9c** [comment]
是否要是没有污染且没有被墙的DNS。
有两个疑问；
这样的DNS还有么？
如果有，比起直接换成那个DNS，cnds的优势是？

**Comment by semigodking** [comment]
不一定是没有污染的，但一定是要DNS发回来的正确结果也能够收到server。如果对方发的结果完全收不到，那谁也没办法是不？有没有
这样的DNS，要看你的ISP。CDNS的目的是帮你把正确response从多个responses中找出来。同时，它会尝试向两个服务器发送请求，取最先收到的正确结果给你。所以，它的优势也就是：你使用的上游服务器有多快，它就多快，同时有一定的抗丢包能力。你也不需要任何vpn之类的帮忙。
