### ISSUE TITLE
unstable

### ISSUE THREAD

**Issue by wang20150419** [semigodking/cdns#3]
经过这几天的试用，发现有时候还是被污染了。

**Comment by semigodking** [comment]
请偿试抓被污染域名的包。

**Comment by wang20150419** [comment]
我可以试着做测试，但linux不大熟悉。希望提供脚本。

**Comment by semigodking** [comment]
首先，你要知道哪些是被污染了，然后用tcp dump把通信过程抓下来发过来即可。

tcpdump -nvxi eth0 -w /tmp/cdns.pcap udp port 53

根据具体情况把上面命令的网口换成你的wan口，然后运行。
运行后到新窗口查询被污染的dns，如
nslookup ABC.com
或 dig ABC.com
多查询几个，然后把tcpdump ctrl+c 了。将/tmp/cdns.pcap和你查询过程的窗口内容一起发给我既可。

**Comment by semigodking** [comment]
忘说了，要多次查询，直到你看到污染的结果哦

**Comment by wang20150419** [comment]
好的。
我两个不同的网络，都用cdns，要等机会，每次设定的dns ip 也不大一样，不知道是否能重现。
我下决心用这个方案两次，结果都是第2天就出现了污染，就换方案了。
但又不大甘心，认为这是个最优秀的方案，程序小，速度快，比chinadns稳定（常常DNS查询卡死），所以上来冒泡。

**Comment by semigodking** [comment]
如果有必要的话我就加入新杀器

2016年10月29日 17:20，"wang20150419" notifications@github.com写道：

**Comment by wang20150419** [comment]
路由器运行18小时后，出现了污染现象。cdns配置的两个DNS服务器分别为：
66.220.18.42， 208.67.220.220:443

抓包后，用 wireshark 看了一下，比较怪异：(nslookup www.mitbbs.com)
污染的时候，抓到了向 66.220.18.42发的包，返回值有 93.46.8.89 （错）

重启 cdns和dnsmasq后，可以得到正确结果。抓包看，
向 66.220.18.42发的包，返回值有 93.46.8.89，46.82.174.68, 104.20.62.7，得正确结果 104.20.62.7

感觉出错的时候，cdns 还未等到 正确 的包，就返回了。或许正确的结果根本就到不了了？

**Comment by semigodking** [comment]
好的，谢谢。我回头找时间仔细看看

2016年10月30日 18:59，"wang20150419" notifications@github.com写道：

**Comment by semigodking** [comment]
我更新了代码。加强了返回结果的验证。请用新版本测试。
注意：因为没有见到你抓的包，所以我也不知道你遇到的具体情况是什么样子的。所以，只是根据猜测，加强返回结果验证。应该可以较大程度上解决污染问题，但不保证100%。
新防污方法我并不想过早使用，未经长期测试，也免得漏洞被堵。

**Comment by wang20150419** [comment]
谢谢，我再试试。如果还是有污染，我会在这里反馈。

**Comment by wang20150419** [comment]
现在路由器运行14小时，还是有污染。

**Comment by semigodking** [comment]
那没有相应的抓包我很难知道原因了。就算偶尔有漏的，绝大多数假回复也会在黑名单时被过滤掉啊。

**Comment by semigodking** [comment]
突然想到一种可能，你配的dns里有不适合这个程序的。仔细看程序启动时的log，看是不是每个配的dns都有相应的 cool 一句。最好只用我贴子里给出的几个dns做测试。

**Comment by wang20150419** [comment]
我选择的是相对我而言速度最快的DNS服务器，log里有 cool!
1478088983.833008 main.c:264 start_server(...) cdns started
1478088983.995037 cdns.c:613 test_readcb(...) Cool! DNS server 66.220.18.42:53 supports EDNS with UDP payload size: 4096
1478088983.996699 cdns.c:613 test_readcb(...) Cool! DNS server 208.67.220.220:443 supports EDNS with UDP payload size: 4096

**Comment by semigodking** [comment]
你先用8.8.8.8试试。那个443端口的opendns之前验过一次，那个不行。

**Comment by wang20150419** [comment]
好，有结果再反馈。

**Comment by wang20150419** [comment]
路由器运行2小时，BUG再现。从抓包看，正确解析包已经到了，但cdns取的是错误结果。

DNS设置： 66.220.18.42， 8.8.8.8

现象：
nslookup  xys.org
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      xys.org
Address 1: 200:2:5d2e:859::
Address 2: 93.46.8.89 93-46-8-89.ip105.fastwebnet.it

抓包结果（x.x.x.x 为路由器外网IP）：
source     destination   protocol  length   info
x.x.x.x       8.8.8.8           DNS        78         Standard query 0x7b8a A xys.org OPT
8.8.8.8      x.x.x.x            DNS        83         Standard query response 0x7b8a A xys.org A 93.46.8.89
8.8.8.8      x.x.x.x            DNS        90         Standard query response 0x7b8a A xys.org A 93.46.8.89
8.8.8.8      x.x.x.x            DNS        94         Standard query response 0x7b8a A xys.org A 142.4.16.124 OPT

**Comment by semigodking** [comment]
请把你抓的包发给我一份，谢谢

2016年11月3日 00:41，"wang20150419" notifications@github.com写道：

**Comment by wang20150419** [comment]
已发你gmail。

**Comment by semigodking** [comment]
在不同平台上做了数千次查询未能重现问题。你那是什么硬件？什么软件平台？根据你抓的包来看，没理由啊。93打头的IP肯定是会被放入黑名单的，怎么也没理由反回这个结果。你查查你的dnsmasq之类的配置，看有没有问题。

2016年11月3日 13:12，"wang20150419" notifications@github.com写道：

**Comment by wang20150419** [comment]
路由器： netgear WNDR4300 , openwrt chaos calmer 15.05.1
当有污染的时候，重启 cdns 就正常了。cdns 和 dnsmasq 的配置都没问题呀。
（我常用dns2socks通过 socks5 解析国外域名，这个比较稳定，chinadns有随机
偶发的DNS查询死机，透明翻墙就是用你的 redsocks2）

cdns config:
{
    "global": {
    "daemon": true,
    "log": "file:/var/log/cdns.log",
    "pidfile": "/var/run/cdns.pid",
    "log_debug": true
    },
    "cdns": {
        "listen_ip": "127.0.0.1",
        "listen_port": 1053,
        "timeout": 2,
        "servers": [
        {
            "ip_port": "66.220.18.42"
        },
        {
            "ip_port": "8.8.8.8"
        }
        ]
    }
}

dnsmasq.conf:

no-resolv
no-poll
server=127.0.0.1#1053
conf-dir=/etc/dnsmasq.d

(dnsmasq.d 里，配置的是国内常用域名使用本地DNS解析)

**Comment by semigodking** [comment]
真是奇怪的问题。我会继续跟进

**Comment by semigodking** [comment]
发现一种情况会被污染：
ＣＤＮＳ启动的时候，网络如果还没有ready，cdns在对dns server做检测时就会全部失败，cdns后面不会再尝试检测这些server,也没有足够信息做出正确过滤判断，于是会返回被污染的结果。这种情况下，重启cdns后，当时如果网络ready，它就能重新完成检测工作。在这以后，应该就不会再返回污染结果。我回头会fix这种情况。

**Comment by semigodking** [comment]
Commit 7f064d05516f511d80adc99ce831e187e2d0b35a should have this issue fixed. Please open a new issue if you still have similar issue.
