### ISSUE TITLE
how to cross-compile on netgear platform or merlin

### ISSUE THREAD

**Issue by kalagxw** [semigodking/cdns#4]
use toolchain hndtools-arm-linux-2.6.36-uclibc-4.5.3.tar.bz2

**Comment by semigodking** [comment]
What's the problem you encountered during the compiling?

**Comment by kalagxw** [comment]
just can not find .h head file
cannot describe probably，not good at it.
maybe you can try and make an wiki
the toolchain lays in https://github.com/RMerl/asuswrt-merlin.git 
https://github.com/RMerl/asuswrt-merlin/tree/master/release/src-rt-6.x.4708/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3

**Comment by semigodking** [comment]
So, you should add proper include path and library path into environment variable CFLAGS. You can reference section about building for openwrt in readme.
E.g.
export CFLAGS="-I/path/to/include -L/path/to/lib"

**Comment by kalagxw** [comment]
arm-brcm-linux-uclibcgnueabi-gcc -c -o main.o main.c -I/projects/arm/include -L/projects/arm/lib -fPIC -O3 -D_BSD_SOURCE -D_DEFAULT_SOURCE -Wall -std=c99 -D_XOPEN_SOURCE=600
main.c:28:18: fatal error: argp.h: No such file or directory
compilation terminated.
make: *** [main.o] Error 1

**Comment by kalagxw** [comment]
success close
