### ISSUE TITLE
Complie failed in openwrt (LEDE) SDK - dns.h

### ISSUE THREAD

**Issue by hqvv** [semigodking/cdns#5]
Hi test0x01,

Please help on this.
Thanks

In file included from dns.c:22:0:
dns.h:72:14: error: duplicate member 'rd'
     unsigned rd: 1;     /* recursion desired */
              ^
dns.h:73:14: error: duplicate member 'tc'
     unsigned tc: 1;     /* truncated message */
              ^
dns.h:74:14: error: duplicate member 'aa'
     unsigned aa: 1;     /* authoritive answer */
              ^
dns.h:75:14: error: duplicate member 'opcode'
     unsigned opcode: 4; /* purpose of message */
              ^
dns.h:76:14: error: duplicate member 'qr'
     unsigned qr: 1;     /* response flag */
              ^
dns.h:78:14: error: duplicate member 'rcode'
     unsigned rcode: 4;  /* response code */
              ^
dns.h:79:14: error: duplicate member 'cd'
     unsigned cd: 1;
              ^
dns.h:80:14: error: duplicate member 'ad'
     unsigned ad: 1;
              ^
dns.h:81:14: error: duplicate member 'z'
     unsigned z: 1;      /* reserved */
              ^
dns.h:82:14: error: duplicate member 'ra'
     unsigned ra: 1;     /* recursion available */
              ^
Makefile:13: recipe for target 'dns.o' failed

**Comment by semigodking** [comment]
That's strange. How could BYTE_ORDER have different definitions at the same
time?  I have no environment for test. You can try to compile it by
removing unnecessary definitions according to target platform.

2016年11月2日 12:47，"Hanqing" notifications@github.com写道：

**Comment by semigodking** [comment]
Resolved!
