### ISSUE TITLE
江苏电信 直接返回FakeIP

### ISSUE THREAD

**Issue by niphor** [semigodking/cdns#8]
江苏电信似乎不可用，直接返回假的IP

TCPDUMP的结果我发你邮箱了，不知道抓的对不对，如果需要我可以重抓

**Comment by semigodking** [comment]
没见到附件啊

2016年12月14日 22:44，"niphor" <notifications@github.com>写道：

**Comment by niphor** [comment]
额 我单独发的邮件。。。

没有么 那我这边再传个zip压缩包的。。。

2016-12-14 22:51 GMT+08:00 semigodking <notifications@github.com>:

**Comment by semigodking** [comment]
根据你的数据来分析，可以得到如下结论：
１.　你的线路到外部ＤＮＳ的请求是被劫持了的。Google DNS 8.8.8.8/8.8.4.4只支持长度为512的ＵＤＰ包，但你的返回结果中显示支持4096的ＵＤＰ包。　wall返回污染的ＤＮＳ　response是不带EDNS OPT的。但你的线路是返回的。由此可见，你这个线路的ＤＮＳ都是被劫持了的，上级ＤＮＳ也就不会返回正确结果给ＣＤＮＳ的。
２.　对其它境外ＤＮＳ的请求可能被丢弃了。　ＣＤＮＳ会同时给两个ＤＮＳ发送同一请求。在你这线路上，境外ＤＮＳ的请求都没有得到响应，只有wall的抢答。
所以，ＣＤＮＳ在你这里是没法正常使用的。你可以尝试使用非５３端口的ＤＮＳ做upstream server，如果还是这种情况的话，你只能选择其它方式了。比如：dnscrypt, DNS over TCP。

**Comment by niphor** [comment]
嗯 是的

用你的redsock2做udp转发 8.8.8.8 就是512的
但是 redsocks2 的转发的dns请求 chinadns 就直接不会用,导致外国域名就没法解析
cdns的话 看来2台上游都必须是 tcp或者非53的,不然还是会被劫持


在 2016年12月15日 上午10:19，semigodking <notifications@github.com>写道：

**Comment by semigodking** [comment]
对于被劫持这种情况，就象你说的，使用非标端口或tcp dns算是比较好的方法了。

2016-12-15 10:33 GMT+08:00 niphor <notifications@github.com>:

**Comment by niphor** [comment]
好的 谢谢你的解答

在 2016年12月15日 上午10:37，semigodking <notifications@github.com>写道：

**Comment by niphor** [comment]
问下 4096 长度的一般都是有问题的么？
tcp试了114似乎不能tcp，国内129 是4096，202.14.67.4 也是4096

**Comment by semigodking** [comment]
4096并不是问题，那只代表服务器所支持的udp请求长度。在cdns里使用国内dns做上游服务是没用的，只会得到错误结果。
