### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by y9c** [semigodking/cdns#9]
I clone this repo, and make a binary in linux desktop.

I start the program as the instruction, but nothing happened.

```bash
./cdns -c ./config.json
```

---

The responsed ip of `drill` command doesn't change.

**Comment by semigodking** [comment]
Then, you must expect some thing magical to happen. 
When cdns is running, it is listening on a configured port for DNS requests. You have to send DNS requests to it. E.g. by making changes to /etc/resolv.conf

**Comment by y9c** [comment]
Thank you for your reply. 

I start a process on local machine, and use `dig/drill` command to test the DNS resolving.

It seems that the program is not so robust. I run dig command multiple time but he response is diverse.

```bash
$ dig @127.0.0.1 -p 1053 google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 1053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56180
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		652	IN	A	172.217.27.142

;; Query time: 3 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Sun Aug 06 00:24:59 CST 2017
;; MSG SIZE  rcvd: 55

```

```bash
$ dig @127.0.0.1 -p 1053 google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @127.0.0.1 -p 1053 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44534
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		59	IN	A	216.58.200.14

;; AUTHORITY SECTION:
google.com.		35613	IN	NS	ns3.google.com.
google.com.		35613	IN	NS	ns2.google.com.
google.com.		35613	IN	NS	ns1.google.com.
google.com.		35613	IN	NS	ns4.google.com.

;; ADDITIONAL SECTION:
ns2.google.com.		35958	IN	A	216.239.34.10
ns1.google.com.		35958	IN	A	216.239.32.10
ns4.google.com.		35958	IN	A	216.239.38.10
ns3.google.com.		35958	IN	A	216.239.36.10

;; Query time: 51 msec
;; SERVER: 127.0.0.1#1053(127.0.0.1)
;; WHEN: Sun Aug 06 00:25:41 CST 2017
;; MSG SIZE  rcvd: 191

```

```bash
$ dig @1.2.4.8 -p 53 google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @1.2.4.8 -p 53 google.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38041
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		250	IN	A	172.217.27.142

;; Query time: 36 msec
;; SERVER: 1.2.4.8#53(1.2.4.8)
;; WHEN: Sun Aug 06 00:18:08 CST 2017
;; MSG SIZE  rcvd: 55

```

**Comment by y9c** [comment]
I also don't know how to edit the configuration file.

- To trade off the speed and accuracy, shall I use a polluted DNS address and clean one?
-  Does the order in the json file matters?
 - Is there any difference between `8.8.8.8:53` and `8.8.8.8` ? Why don't you set port for the first ip address?
 - What is the limit of ip address to specified? Can I use more than two address?

```json
        {
            "ip_port": "203.80.96.10"
        },
        {
            "ip_port": "8.8.8.8:53"
        }
```

**Comment by semigodking** [comment]
Diverse results are expected. Because the upstream dns servers are
different and they usually return IP's close to themselves.
You should never include any poisoned upstream server, otherwise, you will
get poisoned results. Instead, you should try to configure more upstream
DNS servers having low latency.
Order in config file does NOT matter.
There's no difference between 8.8.8.8:53 and 8.8.8.8 .  This is just to
show you how to specify port number. Port number is 53 by default.
Sure you can add more upstream DNS servers, up to 16 servers.

**Comment by y9c** [comment]
I try to use cdns with shadowsocks in openwrt platform, but don't know how to set up.
Is there any manual to follow?

ChinaDNS set up:
```
## foreign
dnsmasq->ChinaDNS->ss-tunnel->ss server->8.8.8.8
## domestic
dnsmasq->ChinaDNS->114.114.114.114
```
By replacing ChinaDNS with cdns, is it necessary to configure dnsmasq?

**Comment by y9c** [comment]
@semigodking 
However, why IP address returned by `127.0.0.1` is same as response of `1.2.4.8` , which is a poisoned server?

I test the default setting by merely using `203.80.96.10`  and `8.8.8.8` as upstream server.

**Comment by semigodking** [comment]
Two steps:
1. In dnsmasq, use cdns as upstream server.
2. Ensure /etc/resolv.conf contains your dnsmasq as only dns server

yech <notifications@github.com>于2017年8月6日周日 00:55写道：

**Comment by y9c** [comment]
Is there a prebuild ipk file for LEDE system in WNDR4300 router?

**Comment by y9c** [comment]
Would you please complete this manual for me?

https://gist.github.com/yech1990/d797b3fd1737c674f3150289c9928fc1

**Comment by semigodking** [comment]
for all your three questions is no.

yech <notifications@github.com>于2017年8月7日周一 13:07写道：
